workflows:
  capacitor-ios:
    name: Build iOS
    max_build_duration: 60
    environment:
      node: latest
      xcode: latest
    scripts:
      - npm install
      - npm run build
      - npx cap sync ios
      - cd ios/App/App
      - xcodebuild -project App.xcodeproj -scheme App -sdk iphoneos -configuration Release archive -archivePath build/App.xcarchive
    artifacts:
      - ios/App/App/build/**/*.xcarchive
      - ios/App/App/build/**/*.ipa
